### ISSUE TITLE
Fix mobile view of index page

### ISSUE THREAD

**Issue by akamburov** [eth-sri/silq-webpage#9]
On the first page, when you open the site with a mobile browser, you're greeted with a component with 3 columns of text which renders 2-3 letters per line.
It basically looks like a test for the user but i assume this is not intended.
On mobile devices, limited width, the 3 columns should fall one under the other and decrease to 2 or even 1 column.
![Screenshot_20221220-025520_Firefox](https://user-images.githubusercontent.com/2730050/208557149-ff12cf14-43a6-4010-abc7-5b8292b5ebae.jpg)

**Comment by bichselb** [comment]
Should be resolved now thanks to a fix by Hristo Venev, thanks for reporting!
